# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/6im2/ejarcet/OpenGL/glTF-VIEWER-ROOT/gltf-viewer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/6im2/ejarcet/OpenGL/glTF-VIEWER-ROOT/gltf-viewer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/6im2/ejarcet/OpenGL/glTF-VIEWER-ROOT/gltf-viewer/CMakeFiles /home/6im2/ejarcet/OpenGL/glTF-VIEWER-ROOT/gltf-viewer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/6im2/ejarcet/OpenGL/glTF-VIEWER-ROOT/gltf-viewer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gltf-viewer

# Build rule for target.
gltf-viewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gltf-viewer
.PHONY : gltf-viewer

# fast build rule for target.
gltf-viewer/fast:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/build
.PHONY : gltf-viewer/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f third-party/glfw-3.3.1/CMakeFiles/uninstall.dir/build.make third-party/glfw-3.3.1/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f third-party/glfw-3.3.1/src/CMakeFiles/glfw.dir/build.make third-party/glfw-3.3.1/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

apps/gltf-viewer/ViewerApplication.o: apps/gltf-viewer/ViewerApplication.cpp.o

.PHONY : apps/gltf-viewer/ViewerApplication.o

# target to build an object file
apps/gltf-viewer/ViewerApplication.cpp.o:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/ViewerApplication.cpp.o
.PHONY : apps/gltf-viewer/ViewerApplication.cpp.o

apps/gltf-viewer/ViewerApplication.i: apps/gltf-viewer/ViewerApplication.cpp.i

.PHONY : apps/gltf-viewer/ViewerApplication.i

# target to preprocess a source file
apps/gltf-viewer/ViewerApplication.cpp.i:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/ViewerApplication.cpp.i
.PHONY : apps/gltf-viewer/ViewerApplication.cpp.i

apps/gltf-viewer/ViewerApplication.s: apps/gltf-viewer/ViewerApplication.cpp.s

.PHONY : apps/gltf-viewer/ViewerApplication.s

# target to generate assembly for a file
apps/gltf-viewer/ViewerApplication.cpp.s:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/ViewerApplication.cpp.s
.PHONY : apps/gltf-viewer/ViewerApplication.cpp.s

apps/gltf-viewer/main.o: apps/gltf-viewer/main.cpp.o

.PHONY : apps/gltf-viewer/main.o

# target to build an object file
apps/gltf-viewer/main.cpp.o:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/main.cpp.o
.PHONY : apps/gltf-viewer/main.cpp.o

apps/gltf-viewer/main.i: apps/gltf-viewer/main.cpp.i

.PHONY : apps/gltf-viewer/main.i

# target to preprocess a source file
apps/gltf-viewer/main.cpp.i:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/main.cpp.i
.PHONY : apps/gltf-viewer/main.cpp.i

apps/gltf-viewer/main.s: apps/gltf-viewer/main.cpp.s

.PHONY : apps/gltf-viewer/main.s

# target to generate assembly for a file
apps/gltf-viewer/main.cpp.s:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/main.cpp.s
.PHONY : apps/gltf-viewer/main.cpp.s

apps/gltf-viewer/tiny_gltf_impl.o: apps/gltf-viewer/tiny_gltf_impl.cpp.o

.PHONY : apps/gltf-viewer/tiny_gltf_impl.o

# target to build an object file
apps/gltf-viewer/tiny_gltf_impl.cpp.o:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/tiny_gltf_impl.cpp.o
.PHONY : apps/gltf-viewer/tiny_gltf_impl.cpp.o

apps/gltf-viewer/tiny_gltf_impl.i: apps/gltf-viewer/tiny_gltf_impl.cpp.i

.PHONY : apps/gltf-viewer/tiny_gltf_impl.i

# target to preprocess a source file
apps/gltf-viewer/tiny_gltf_impl.cpp.i:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/tiny_gltf_impl.cpp.i
.PHONY : apps/gltf-viewer/tiny_gltf_impl.cpp.i

apps/gltf-viewer/tiny_gltf_impl.s: apps/gltf-viewer/tiny_gltf_impl.cpp.s

.PHONY : apps/gltf-viewer/tiny_gltf_impl.s

# target to generate assembly for a file
apps/gltf-viewer/tiny_gltf_impl.cpp.s:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/tiny_gltf_impl.cpp.s
.PHONY : apps/gltf-viewer/tiny_gltf_impl.cpp.s

apps/gltf-viewer/utils/cameras.o: apps/gltf-viewer/utils/cameras.cpp.o

.PHONY : apps/gltf-viewer/utils/cameras.o

# target to build an object file
apps/gltf-viewer/utils/cameras.cpp.o:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/utils/cameras.cpp.o
.PHONY : apps/gltf-viewer/utils/cameras.cpp.o

apps/gltf-viewer/utils/cameras.i: apps/gltf-viewer/utils/cameras.cpp.i

.PHONY : apps/gltf-viewer/utils/cameras.i

# target to preprocess a source file
apps/gltf-viewer/utils/cameras.cpp.i:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/utils/cameras.cpp.i
.PHONY : apps/gltf-viewer/utils/cameras.cpp.i

apps/gltf-viewer/utils/cameras.s: apps/gltf-viewer/utils/cameras.cpp.s

.PHONY : apps/gltf-viewer/utils/cameras.s

# target to generate assembly for a file
apps/gltf-viewer/utils/cameras.cpp.s:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/utils/cameras.cpp.s
.PHONY : apps/gltf-viewer/utils/cameras.cpp.s

apps/gltf-viewer/utils/gl_debug_output.o: apps/gltf-viewer/utils/gl_debug_output.cpp.o

.PHONY : apps/gltf-viewer/utils/gl_debug_output.o

# target to build an object file
apps/gltf-viewer/utils/gl_debug_output.cpp.o:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/utils/gl_debug_output.cpp.o
.PHONY : apps/gltf-viewer/utils/gl_debug_output.cpp.o

apps/gltf-viewer/utils/gl_debug_output.i: apps/gltf-viewer/utils/gl_debug_output.cpp.i

.PHONY : apps/gltf-viewer/utils/gl_debug_output.i

# target to preprocess a source file
apps/gltf-viewer/utils/gl_debug_output.cpp.i:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/utils/gl_debug_output.cpp.i
.PHONY : apps/gltf-viewer/utils/gl_debug_output.cpp.i

apps/gltf-viewer/utils/gl_debug_output.s: apps/gltf-viewer/utils/gl_debug_output.cpp.s

.PHONY : apps/gltf-viewer/utils/gl_debug_output.s

# target to generate assembly for a file
apps/gltf-viewer/utils/gl_debug_output.cpp.s:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/utils/gl_debug_output.cpp.s
.PHONY : apps/gltf-viewer/utils/gl_debug_output.cpp.s

apps/gltf-viewer/utils/gltf.o: apps/gltf-viewer/utils/gltf.cpp.o

.PHONY : apps/gltf-viewer/utils/gltf.o

# target to build an object file
apps/gltf-viewer/utils/gltf.cpp.o:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/utils/gltf.cpp.o
.PHONY : apps/gltf-viewer/utils/gltf.cpp.o

apps/gltf-viewer/utils/gltf.i: apps/gltf-viewer/utils/gltf.cpp.i

.PHONY : apps/gltf-viewer/utils/gltf.i

# target to preprocess a source file
apps/gltf-viewer/utils/gltf.cpp.i:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/utils/gltf.cpp.i
.PHONY : apps/gltf-viewer/utils/gltf.cpp.i

apps/gltf-viewer/utils/gltf.s: apps/gltf-viewer/utils/gltf.cpp.s

.PHONY : apps/gltf-viewer/utils/gltf.s

# target to generate assembly for a file
apps/gltf-viewer/utils/gltf.cpp.s:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/utils/gltf.cpp.s
.PHONY : apps/gltf-viewer/utils/gltf.cpp.s

apps/gltf-viewer/utils/images.o: apps/gltf-viewer/utils/images.cpp.o

.PHONY : apps/gltf-viewer/utils/images.o

# target to build an object file
apps/gltf-viewer/utils/images.cpp.o:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/utils/images.cpp.o
.PHONY : apps/gltf-viewer/utils/images.cpp.o

apps/gltf-viewer/utils/images.i: apps/gltf-viewer/utils/images.cpp.i

.PHONY : apps/gltf-viewer/utils/images.i

# target to preprocess a source file
apps/gltf-viewer/utils/images.cpp.i:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/utils/images.cpp.i
.PHONY : apps/gltf-viewer/utils/images.cpp.i

apps/gltf-viewer/utils/images.s: apps/gltf-viewer/utils/images.cpp.s

.PHONY : apps/gltf-viewer/utils/images.s

# target to generate assembly for a file
apps/gltf-viewer/utils/images.cpp.s:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/apps/gltf-viewer/utils/images.cpp.s
.PHONY : apps/gltf-viewer/utils/images.cpp.s

third-party/glad/src/glad.o: third-party/glad/src/glad.c.o

.PHONY : third-party/glad/src/glad.o

# target to build an object file
third-party/glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/glad/src/glad.c.o
.PHONY : third-party/glad/src/glad.c.o

third-party/glad/src/glad.i: third-party/glad/src/glad.c.i

.PHONY : third-party/glad/src/glad.i

# target to preprocess a source file
third-party/glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/glad/src/glad.c.i
.PHONY : third-party/glad/src/glad.c.i

third-party/glad/src/glad.s: third-party/glad/src/glad.c.s

.PHONY : third-party/glad/src/glad.s

# target to generate assembly for a file
third-party/glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/glad/src/glad.c.s
.PHONY : third-party/glad/src/glad.c.s

third-party/imgui-1.74/examples/imgui_impl_glfw.o: third-party/imgui-1.74/examples/imgui_impl_glfw.cpp.o

.PHONY : third-party/imgui-1.74/examples/imgui_impl_glfw.o

# target to build an object file
third-party/imgui-1.74/examples/imgui_impl_glfw.cpp.o:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/examples/imgui_impl_glfw.cpp.o
.PHONY : third-party/imgui-1.74/examples/imgui_impl_glfw.cpp.o

third-party/imgui-1.74/examples/imgui_impl_glfw.i: third-party/imgui-1.74/examples/imgui_impl_glfw.cpp.i

.PHONY : third-party/imgui-1.74/examples/imgui_impl_glfw.i

# target to preprocess a source file
third-party/imgui-1.74/examples/imgui_impl_glfw.cpp.i:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/examples/imgui_impl_glfw.cpp.i
.PHONY : third-party/imgui-1.74/examples/imgui_impl_glfw.cpp.i

third-party/imgui-1.74/examples/imgui_impl_glfw.s: third-party/imgui-1.74/examples/imgui_impl_glfw.cpp.s

.PHONY : third-party/imgui-1.74/examples/imgui_impl_glfw.s

# target to generate assembly for a file
third-party/imgui-1.74/examples/imgui_impl_glfw.cpp.s:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/examples/imgui_impl_glfw.cpp.s
.PHONY : third-party/imgui-1.74/examples/imgui_impl_glfw.cpp.s

third-party/imgui-1.74/examples/imgui_impl_opengl3.o: third-party/imgui-1.74/examples/imgui_impl_opengl3.cpp.o

.PHONY : third-party/imgui-1.74/examples/imgui_impl_opengl3.o

# target to build an object file
third-party/imgui-1.74/examples/imgui_impl_opengl3.cpp.o:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/examples/imgui_impl_opengl3.cpp.o
.PHONY : third-party/imgui-1.74/examples/imgui_impl_opengl3.cpp.o

third-party/imgui-1.74/examples/imgui_impl_opengl3.i: third-party/imgui-1.74/examples/imgui_impl_opengl3.cpp.i

.PHONY : third-party/imgui-1.74/examples/imgui_impl_opengl3.i

# target to preprocess a source file
third-party/imgui-1.74/examples/imgui_impl_opengl3.cpp.i:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/examples/imgui_impl_opengl3.cpp.i
.PHONY : third-party/imgui-1.74/examples/imgui_impl_opengl3.cpp.i

third-party/imgui-1.74/examples/imgui_impl_opengl3.s: third-party/imgui-1.74/examples/imgui_impl_opengl3.cpp.s

.PHONY : third-party/imgui-1.74/examples/imgui_impl_opengl3.s

# target to generate assembly for a file
third-party/imgui-1.74/examples/imgui_impl_opengl3.cpp.s:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/examples/imgui_impl_opengl3.cpp.s
.PHONY : third-party/imgui-1.74/examples/imgui_impl_opengl3.cpp.s

third-party/imgui-1.74/imgui.o: third-party/imgui-1.74/imgui.cpp.o

.PHONY : third-party/imgui-1.74/imgui.o

# target to build an object file
third-party/imgui-1.74/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/imgui.cpp.o
.PHONY : third-party/imgui-1.74/imgui.cpp.o

third-party/imgui-1.74/imgui.i: third-party/imgui-1.74/imgui.cpp.i

.PHONY : third-party/imgui-1.74/imgui.i

# target to preprocess a source file
third-party/imgui-1.74/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/imgui.cpp.i
.PHONY : third-party/imgui-1.74/imgui.cpp.i

third-party/imgui-1.74/imgui.s: third-party/imgui-1.74/imgui.cpp.s

.PHONY : third-party/imgui-1.74/imgui.s

# target to generate assembly for a file
third-party/imgui-1.74/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/imgui.cpp.s
.PHONY : third-party/imgui-1.74/imgui.cpp.s

third-party/imgui-1.74/imgui_demo.o: third-party/imgui-1.74/imgui_demo.cpp.o

.PHONY : third-party/imgui-1.74/imgui_demo.o

# target to build an object file
third-party/imgui-1.74/imgui_demo.cpp.o:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/imgui_demo.cpp.o
.PHONY : third-party/imgui-1.74/imgui_demo.cpp.o

third-party/imgui-1.74/imgui_demo.i: third-party/imgui-1.74/imgui_demo.cpp.i

.PHONY : third-party/imgui-1.74/imgui_demo.i

# target to preprocess a source file
third-party/imgui-1.74/imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/imgui_demo.cpp.i
.PHONY : third-party/imgui-1.74/imgui_demo.cpp.i

third-party/imgui-1.74/imgui_demo.s: third-party/imgui-1.74/imgui_demo.cpp.s

.PHONY : third-party/imgui-1.74/imgui_demo.s

# target to generate assembly for a file
third-party/imgui-1.74/imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/imgui_demo.cpp.s
.PHONY : third-party/imgui-1.74/imgui_demo.cpp.s

third-party/imgui-1.74/imgui_draw.o: third-party/imgui-1.74/imgui_draw.cpp.o

.PHONY : third-party/imgui-1.74/imgui_draw.o

# target to build an object file
third-party/imgui-1.74/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/imgui_draw.cpp.o
.PHONY : third-party/imgui-1.74/imgui_draw.cpp.o

third-party/imgui-1.74/imgui_draw.i: third-party/imgui-1.74/imgui_draw.cpp.i

.PHONY : third-party/imgui-1.74/imgui_draw.i

# target to preprocess a source file
third-party/imgui-1.74/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/imgui_draw.cpp.i
.PHONY : third-party/imgui-1.74/imgui_draw.cpp.i

third-party/imgui-1.74/imgui_draw.s: third-party/imgui-1.74/imgui_draw.cpp.s

.PHONY : third-party/imgui-1.74/imgui_draw.s

# target to generate assembly for a file
third-party/imgui-1.74/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/imgui_draw.cpp.s
.PHONY : third-party/imgui-1.74/imgui_draw.cpp.s

third-party/imgui-1.74/imgui_widgets.o: third-party/imgui-1.74/imgui_widgets.cpp.o

.PHONY : third-party/imgui-1.74/imgui_widgets.o

# target to build an object file
third-party/imgui-1.74/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/imgui_widgets.cpp.o
.PHONY : third-party/imgui-1.74/imgui_widgets.cpp.o

third-party/imgui-1.74/imgui_widgets.i: third-party/imgui-1.74/imgui_widgets.cpp.i

.PHONY : third-party/imgui-1.74/imgui_widgets.i

# target to preprocess a source file
third-party/imgui-1.74/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/imgui_widgets.cpp.i
.PHONY : third-party/imgui-1.74/imgui_widgets.cpp.i

third-party/imgui-1.74/imgui_widgets.s: third-party/imgui-1.74/imgui_widgets.cpp.s

.PHONY : third-party/imgui-1.74/imgui_widgets.s

# target to generate assembly for a file
third-party/imgui-1.74/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/gltf-viewer.dir/build.make CMakeFiles/gltf-viewer.dir/third-party/imgui-1.74/imgui_widgets.cpp.s
.PHONY : third-party/imgui-1.74/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... gltf-viewer"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... apps/gltf-viewer/ViewerApplication.o"
	@echo "... apps/gltf-viewer/ViewerApplication.i"
	@echo "... apps/gltf-viewer/ViewerApplication.s"
	@echo "... apps/gltf-viewer/main.o"
	@echo "... apps/gltf-viewer/main.i"
	@echo "... apps/gltf-viewer/main.s"
	@echo "... apps/gltf-viewer/tiny_gltf_impl.o"
	@echo "... apps/gltf-viewer/tiny_gltf_impl.i"
	@echo "... apps/gltf-viewer/tiny_gltf_impl.s"
	@echo "... apps/gltf-viewer/utils/cameras.o"
	@echo "... apps/gltf-viewer/utils/cameras.i"
	@echo "... apps/gltf-viewer/utils/cameras.s"
	@echo "... apps/gltf-viewer/utils/gl_debug_output.o"
	@echo "... apps/gltf-viewer/utils/gl_debug_output.i"
	@echo "... apps/gltf-viewer/utils/gl_debug_output.s"
	@echo "... apps/gltf-viewer/utils/gltf.o"
	@echo "... apps/gltf-viewer/utils/gltf.i"
	@echo "... apps/gltf-viewer/utils/gltf.s"
	@echo "... apps/gltf-viewer/utils/images.o"
	@echo "... apps/gltf-viewer/utils/images.i"
	@echo "... apps/gltf-viewer/utils/images.s"
	@echo "... third-party/glad/src/glad.o"
	@echo "... third-party/glad/src/glad.i"
	@echo "... third-party/glad/src/glad.s"
	@echo "... third-party/imgui-1.74/examples/imgui_impl_glfw.o"
	@echo "... third-party/imgui-1.74/examples/imgui_impl_glfw.i"
	@echo "... third-party/imgui-1.74/examples/imgui_impl_glfw.s"
	@echo "... third-party/imgui-1.74/examples/imgui_impl_opengl3.o"
	@echo "... third-party/imgui-1.74/examples/imgui_impl_opengl3.i"
	@echo "... third-party/imgui-1.74/examples/imgui_impl_opengl3.s"
	@echo "... third-party/imgui-1.74/imgui.o"
	@echo "... third-party/imgui-1.74/imgui.i"
	@echo "... third-party/imgui-1.74/imgui.s"
	@echo "... third-party/imgui-1.74/imgui_demo.o"
	@echo "... third-party/imgui-1.74/imgui_demo.i"
	@echo "... third-party/imgui-1.74/imgui_demo.s"
	@echo "... third-party/imgui-1.74/imgui_draw.o"
	@echo "... third-party/imgui-1.74/imgui_draw.i"
	@echo "... third-party/imgui-1.74/imgui_draw.s"
	@echo "... third-party/imgui-1.74/imgui_widgets.o"
	@echo "... third-party/imgui-1.74/imgui_widgets.i"
	@echo "... third-party/imgui-1.74/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

